# Generated by Django 4.2.1 on 2023-05-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_promo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_name", models.CharField(max_length=500)),
                ("app_link", models.URLField()),
                ("app_point", models.FloatField(default=0)),
                (
                    "app_icon",
                    models.ImageField(default="default.jpg", upload_to="app_icon.jpg"),
                ),
            ],
        ),
    ]
