# Generated by Django 4.2.1 on 2023-05-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_promo", "0005_adminuser_is_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminuser",
            name="is_admin",
        ),
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
