# Generated by Django 4.2.1 on 2023-05-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_promo", "0006_remove_adminuser_is_admin_user_is_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="app_link",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="app",
            name="app_point",
            field=models.IntegerField(default=0),
        ),
    ]
