# Generated by Django 4.2.1 on 2023-05-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_promo", "0007_alter_app_app_link_alter_app_app_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="app_point",
            field=models.FloatField(default=0),
        ),
    ]
