# Generated by Django 4.2.1 on 2023-05-19 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app_promo", "0008_alter_app_app_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
