# Generated by Django 4.2.1 on 2023-05-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_promo", "0010_remove_app_app_link_app_app_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="app_category",
            field=models.CharField(
                choices=[
                    ("SN", "Social Networking"),
                    ("ENT", "Entertainment"),
                    ("PROD", "Productivity"),
                    ("EDU", "Education"),
                    ("FIT", "Health & Fitness"),
                    ("TRAV", "Travel"),
                    ("FIN", "Finance"),
                    ("NEWS", "News & Magazines"),
                    ("MUSIC", "Music"),
                    ("PHOTO", "Photography"),
                    ("SHOP", "Shopping"),
                    ("GAME", "Games"),
                    ("SPORT", "Sports"),
                    ("UTIL", "Utilities"),
                    ("WEATH", "Weather"),
                    ("FOOD", "Food & Drink"),
                    ("LIFE", "Lifestyle"),
                    ("BUS", "Business"),
                ],
                max_length=200,
            ),
        ),
    ]
